spring:
  mail:
    host:
    port:
    username:
    password:


    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable:
          connectiontimeout:
          timeout:
          writeTimeout:





